Import numpy as np and print the version number.

In [24]:
import numpy as np
np.__version__

'1.16.2'

Create a 1D array of numbers from 0 to 9

In [25]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


Create a 3×3 numpy array of all True’s

In [27]:
np.ones((3,3),dtype = bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])


Extract all odd numbers from arr

In [89]:
a = np.array(range(9)).reshape(3,3)
print(a)
b = np.random.randint(0,100,9)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[47 84 42 24 18  5 38 36 19]


In [42]:
print(a[a%2!=0])
print(b[b%2!=0])

[1 3 5 7]
[59 77 23]


Replace all odd numbers in arr with -1

In [43]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [45]:
a[a%2!=0] = -1
a

array([[ 0, -1,  2],
       [-1,  4, -1],
       [ 6, -1,  8]])

Convert a 1D array to a 2D array with 2 rows

In [54]:
dim1 = np.array([1,2,3,4])
dim1.reshape(2,2)

array([[1, 2],
       [3, 4]])

Stack arrays a and b vertically

a = np.arange(10).reshape(2,-1)<br>
b = np.repeat(1, 10).reshape(2,-1)

In [61]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(a)
print(b)
np.vstack((a,b))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

Stack the arrays a and b horizontally.

In [62]:
np.hstack((a,b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])


Get the positions where elements of a and b match

Input:

a = np.array([1,2,3,2,3,4,3,4,5,6])<br>
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [78]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
a = np.array(np.where(a==b))
print(a.flatten())

[1 3 5 7]



Get all items between 5 and 10 from a.

Input:

a = np.array([2, 6, 1, 9, 10, 3, 27])

In [84]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a>5) & (a<10)]

array([6, 9])

Convert the function maxx that works on two scalars, to work on two arrays.

Input:

def maxx(x, y):<br>
    """Get the maximum of two items"""<br>
    if x >= y:<br>
        return x<br>
    else:<br>
        return y<br>

maxx(1, 5)<br>
#> 5<br>
Desired Output:<br>

a = np.array([5, 7, 9, 8, 6, 4, 5])<br>
b = np.array([6, 3, 4, 8, 9, 7, 1])<br>
pair_max(a, b)<br>
#> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])<br>

In [86]:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
def maxx(x, y):
    if x >= y:
        return x
    else:
        return y
    
vgrater = np.vectorize(maxx)
vgrater(a,b)

array([6, 7, 9, 8, 9, 7, 5])

swap columns 1 and 2 in the array arr.<br>
arr = np.arange(9).reshape(3,3)<br>
arr</pre

In [94]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [96]:
print(arr[[1,0,2]])

[[3 4 5]
 [0 1 2]
 [6 7 8]]


How to reverse the rows of a 2D array?<br>
arr = np.arange(9).reshape(3,3)<br>
arr</pre

In [101]:
arr = np.arange(9).reshape(3,3)
print(arr)
arr.T

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

Reverse the columns of a 2D array arr.<br>
arr = np.arange(9).reshape(3,3)<br>
arr

In [105]:
arr = np.arange(9).reshape(3,3)
np.flip(arr[0])

array([2, 1, 0])

Write a NumPy program to generate five random numbers from the normal distribution

In [ ]:
print(np.random.normal())


Write a NumPy program to generate six random integers between 10 and 30

Write a NumPy program to create a 3x3x3 array with random values


Write a NumPy program to create a 5x5 array with random values and find the minimum and maximum values.


Write a NumPy program to create a random 10x4 array and extract the first five rows of the array and store them into a variable


Write a NumPy program to shuffle numbers between 0 and 10 (inclusive).


Read an JPEG image into a numpy array, return the size and shap of that image